mappings:
  product_reference: "Référence Produit (Code)"
  product_title: "Titre du produit (Description)"
  family: "Famille"
  sub_family: "Sous-Famille"
  brand: "Marque"
  level_1: "Niveau 1"
  level_2: "Niveau 2"
  level_3: "Niveau 3"
  level_4: "Niveau 4"
  tax_rule: "Règle de taxe"
  price_excl_tax: "Prix du Produit HT"
  price_incl_tax: "Prix TTC"
  weight: "Poids"
  ean: "EAN"
  short_description: "Description courte"
  long_description: "Description Longue"
  image: "IMG"
